export interface Feed {
  time: number,
  date: string,
  adminApprove: string,
  category: string,
  postId: string,
  postTitle: string,
  postDescription: string,
  postImage: string,
  userId: string,
  userImage: string,
  userName: string,
}

export interface Donation {
  time: number,
  date: string,
  adminApprove: string,
  category: string,
  donationId: string,
  userId: string,
  userImage: string,
  userName: string,
  donationTitle: string,
  donationType: string,
  donationAmount: number,
  donationDescription: string,
  donationImage: string,
}

export interface LostPet {
  time: number,
  date: string,
  adminApprove: string,
  category: string,
  lostPetId: string,
  userId: string,
  userImage: string,
  userName: string,
  petName: string,
  petGender: string,
  petBreed: string,
  petColor: string,
  lastLocation: string,
  reward: string,
  rewardAmount: number,
  description: string,
  petImage: string,
}
